[package]
name = "categorax"
version = "0.1.0"
edition = "2021"
description = "A friendly terminal-first file and folder tagging tool."
license = "MIT"
repository = "https://github.com/the-sudipta/categorax"
readme = "README.md"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
console = "0.15"
directories = "5.0"
dunce = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

[profile.release]
codegen-units = 1
lto = true
strip = true
